# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployer
        uses: sand4rt/ftp-deployer@v1.3
        with:
          sftp: true # optional
          host: ${{ secrets.REMOTE }} # e.g. ftp.host.com or sftp.host.com
          port: 22 # optional, default is: 21
          username: ${{ secrets.USERNAME }} # FTP username
          password: ${{ secrets.PASSWORD }} # FTP password
          remote_folder: ${{ secrets.FOLDER }} # optional, remote path of your FTP server
          local_folder: ./ # optional, local path, default is: dist
          cleanup: false # optional, remove existing files inside FTP remote folder
          include: '' # optional, e.g.
            # - dist
          exclude: '.github' # optional
          pasive: true # optional
